chat:
  server:
    port: 18080

spring:
  redis:
    host: 114.55.64.45
    port: 6379
    password: Xqq123456

curator:
  #重试retryCount次,当会话超时出现后，curator会每间隔elapsedTimeMs毫秒时间重试一次，共重试retryCount次
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 114.55.64.45:2181,112.124.45.211:2181,112.124.45.211:2180
  #会话超时时间设置
  sessionTimeoutMs: 60000
  #连接超时时间
  connectionTimeoutMs: 5000
  #命名空间
  namespace: metting-server

session:
  expireTime: 7200


