// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerPeerConnectedMessage.proto

package com.xqmetting.protocol;

public final class ServerPeerConnectedMessageOuterClass {
  private ServerPeerConnectedMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerPeerConnectedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerPeerConnectedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Message msg = 1;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.Message msg = 1;</code>
     * @return The msg.
     */
    com.xqmetting.protocol.MessageOuterClass.Message getMsg();
    /**
     * <code>.Message msg = 1;</code>
     */
    com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code ServerPeerConnectedMessage}
   */
  public static final class ServerPeerConnectedMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerPeerConnectedMessage)
      ServerPeerConnectedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerPeerConnectedMessage.newBuilder() to construct.
    private ServerPeerConnectedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerPeerConnectedMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerPeerConnectedMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerPeerConnectedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.xqmetting.protocol.MessageOuterClass.Message.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(com.xqmetting.protocol.MessageOuterClass.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.class, com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private com.xqmetting.protocol.MessageOuterClass.Message msg_;
    /**
     * <code>.Message msg = 1;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.Message msg = 1;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.xqmetting.protocol.MessageOuterClass.Message getMsg() {
      return msg_ == null ? com.xqmetting.protocol.MessageOuterClass.Message.getDefaultInstance() : msg_;
    }
    /**
     * <code>.Message msg = 1;</code>
     */
    @java.lang.Override
    public com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msg_ != null) {
        output.writeMessage(1, getMsg());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage)) {
        return super.equals(obj);
      }
      com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage other = (com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) obj;

      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerPeerConnectedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerPeerConnectedMessage)
        com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.class, com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.Builder.class);
      }

      // Construct using com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
      }

      @java.lang.Override
      public com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstanceForType() {
        return com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage build() {
        com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage buildPartial() {
        com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage result = new com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage(this);
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) {
          return mergeFrom((com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage other) {
        if (other == com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.xqmetting.protocol.MessageOuterClass.Message msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xqmetting.protocol.MessageOuterClass.Message, com.xqmetting.protocol.MessageOuterClass.Message.Builder, com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder> msgBuilder_;
      /**
       * <code>.Message msg = 1;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>.Message msg = 1;</code>
       * @return The msg.
       */
      public com.xqmetting.protocol.MessageOuterClass.Message getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? com.xqmetting.protocol.MessageOuterClass.Message.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public Builder setMsg(com.xqmetting.protocol.MessageOuterClass.Message value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public Builder setMsg(
          com.xqmetting.protocol.MessageOuterClass.Message.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public Builder mergeMsg(com.xqmetting.protocol.MessageOuterClass.Message value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              com.xqmetting.protocol.MessageOuterClass.Message.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public com.xqmetting.protocol.MessageOuterClass.Message.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      public com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              com.xqmetting.protocol.MessageOuterClass.Message.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.Message msg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xqmetting.protocol.MessageOuterClass.Message, com.xqmetting.protocol.MessageOuterClass.Message.Builder, com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xqmetting.protocol.MessageOuterClass.Message, com.xqmetting.protocol.MessageOuterClass.Message.Builder, com.xqmetting.protocol.MessageOuterClass.MessageOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerPeerConnectedMessage)
    }

    // @@protoc_insertion_point(class_scope:ServerPeerConnectedMessage)
    private static final com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage();
    }

    public static com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerPeerConnectedMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerPeerConnectedMessage>() {
      @java.lang.Override
      public ServerPeerConnectedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerPeerConnectedMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerPeerConnectedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerPeerConnectedMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xqmetting.protocol.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerPeerConnectedMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerPeerConnectedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n ServerPeerConnectedMessage.proto\032\rMess" +
      "age.proto\"3\n\032ServerPeerConnectedMessage\022" +
      "\025\n\003msg\030\001 \001(\0132\010.MessageB\030\n\026com.xqmetting." +
      "protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xqmetting.protocol.MessageOuterClass.getDescriptor(),
        });
    internal_static_ServerPeerConnectedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerPeerConnectedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerPeerConnectedMessage_descriptor,
        new java.lang.String[] { "Msg", });
    com.xqmetting.protocol.MessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
