// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/ServerPeerConnectedMessage.proto

package com.xqmetting.protocol.message;

public final class ServerPeerConnectedMessageOuterClass {
  private ServerPeerConnectedMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerPeerConnectedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerPeerConnectedMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ServerPeerConnectedMessage}
   */
  public static final class ServerPeerConnectedMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerPeerConnectedMessage)
      ServerPeerConnectedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerPeerConnectedMessage.newBuilder() to construct.
    private ServerPeerConnectedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerPeerConnectedMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerPeerConnectedMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerPeerConnectedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.class, com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage)) {
        return super.equals(obj);
      }
      com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage other = (com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerPeerConnectedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerPeerConnectedMessage)
        com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.class, com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.Builder.class);
      }

      // Construct using com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.internal_static_ServerPeerConnectedMessage_descriptor;
      }

      @java.lang.Override
      public com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstanceForType() {
        return com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage build() {
        com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage buildPartial() {
        com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage result = new com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) {
          return mergeFrom((com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage other) {
        if (other == com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerPeerConnectedMessage)
    }

    // @@protoc_insertion_point(class_scope:ServerPeerConnectedMessage)
    private static final com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage();
    }

    public static com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerPeerConnectedMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerPeerConnectedMessage>() {
      @java.lang.Override
      public ServerPeerConnectedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerPeerConnectedMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerPeerConnectedMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerPeerConnectedMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xqmetting.protocol.message.ServerPeerConnectedMessageOuterClass.ServerPeerConnectedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerPeerConnectedMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerPeerConnectedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(message/ServerPeerConnectedMessage.pro" +
      "to\"\034\n\032ServerPeerConnectedMessageB \n\036com." +
      "xqmetting.protocol.messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ServerPeerConnectedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerPeerConnectedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerPeerConnectedMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
